#!/usr/bin/env python3
"""
Generate the 12x12 path-collision matrix as a C++ initializer.

Each cell is a 5-element array:
    [0] = 0 no collision, 1 collision
    [1],[2] = x,y of first  collision (0,0 if none)
    [3],[4] = x,y of second collision (0,0 if none)

Reuses build_routes / path_intersections from plot_routes.py.

Usage:
    python gen_collision_matrix.py            # DIM = 90, prints to stdout
    python gen_collision_matrix.py --dim 120
    python gen_collision_matrix.py --dim 90 > collision_matrix.txt

Generated by Claude Opus 4.8
"""

import sys

# import the geometry from the plotting script
from plot_routes import build_routes, path_intersections


def parse_args(argv):
    dim = 90
    i = 0
    while i < len(argv):
        if argv[i] == "--dim":
            dim = float(argv[i + 1]); i += 2; continue
        i += 1
    return dim


def cell(routes, a, b, dim):
    """Return (flag, x1, y1, x2, y2) with coords as fractions of dim."""
    if a == b:
        return [0, 0.0, 0.0, 0.0, 0.0]
    hits = path_intersections(routes[a], routes[b])
    uniq = []
    for h in hits:
        x, y = h["point"]
        if any(abs(x - ux) < 1e-6 and abs(y - uy) < 1e-6 for ux, uy in uniq):
            continue
        uniq.append((x, y))
    uniq = uniq[:2]
    if not uniq:
        return [0, 0.0, 0.0, 0.0, 0.0]
    x1, y1 = uniq[0]
    if len(uniq) >= 2:
        x2, y2 = uniq[1]
    else:
        x2, y2 = 0.0, 0.0
    # store as fractions of dim; C++ reconstructs with * DIM
    return [1, x1/dim, y1/dim, x2/dim, y2/dim]


def fmt(flag, frac):
    """Format one coordinate as a DIM-tied C++ expression."""
    if flag == 0 or abs(frac) < 1e-12:
        return "0"
    return f"{frac:.6f}*DIM"


def main():
    dim = parse_args(sys.argv[1:])
    routes = build_routes(dim)

    print("// Auto-generated path-collision matrix. Coordinates are tied to DIM,")
    print("// so this table is valid for ANY value of DIM (no regeneration needed).")
    print("// res[0] = 0 no collision / 1 collision;")
    print("// res[1],res[2] = x,y of first collision; res[3],res[4] = x,y of second.")
    print("const std::vector<std::vector<std::array<double, 5>>> collisionMatrix = {")
    for a in range(12):
        cells = []
        for b in range(12):
            v = cell(routes, a, b, dim)
            flag = v[0]
            parts = [str(flag)] + [fmt(flag, v[i]) for i in range(1, 5)]
            cells.append("{" + ", ".join(parts) + "}")
        print("    {" + ", ".join(cells) + "},")
    print("};")


if __name__ == "__main__":
    main()