#!/usr/bin/env python3
"""
Generate the 12x12 path-collision matrix as a C++ initializer.

Hybrid model:
  - If two route CENTERLINES cross (genuine intersection), use the exact
    crossing point. Exact and identical from both vehicles' perspective.
  - Else, if the swept BODIES overlap (width W=DIM/15) at a steep angle
    inside the junction, it is a width-induced conflict; use the overlap
    point. Catches near-misses like routes that clip while turning.
  Both cases filtered by incidence >= 25 deg and center-square containment,
  so parallel merges / shared-lane following are excluded.

Each cell: [flag, x1, y1, x2, y2], coords tied to DIM (fractions * DIM).

Usage:
    python gen_collision_matrix.py            # DIM=90
    python gen_collision_matrix.py --dim 120

Generated by Claude Opus 4.8
"""

import sys, math
from GlobalPlans_plotter import build_routes, path_intersections

MIN_INC = 25.0


def parse_args(argv):
    dim = 90
    i = 0
    while i < len(argv):
        if argv[i] == "--dim":
            dim = float(argv[i + 1]); i += 2; continue
        i += 1
    return dim


def centerline_pts(routes, a, b, dim):
    lo, hi = dim/3 - dim/30, 2*dim/3 + dim/30
    u = []
    for h in path_intersections(routes[a], routes[b]):
        if h["incidence"] < MIN_INC:
            continue
        x, y = h["point"]
        if not (lo <= x <= hi and lo <= y <= hi):
            continue
        if any(abs(x - ux) < 1e-6 and abs(y - uy) < 1e-6 for ux, uy in u):
            continue
        u.append((x, y))
    return u[:2]


def densify(pts, step):
    out = []
    for (x0, y0), (x1, y1) in zip(pts, pts[1:]):
        seg = math.hypot(x1 - x0, y1 - y0)
        n = max(1, int(seg / step))
        for k in range(n + 1):
            t = k / n
            out.append((x0 + t*(x1-x0), y0 + t*(y1-y0), x1-x0, y1-y0))
    return out


def body_pts(routes, a, b, dim):
    W = dim / 15.0
    lo, hi = dim/3 - dim/30, 2*dim/3 + dim/30
    step = dim / 225.0
    A = densify(routes[a], step); B = densify(routes[b], step)
    raw = []
    for (ax, ay, adx, ady) in A:
        bestd = 1e9; rep = None
        for (bx, by, bdx, bdy) in B:
            d = math.hypot(ax - bx, ay - by)
            if d < bestd:
                bestd = d
                aa = math.degrees(math.atan2(ady, adx))
                ba = math.degrees(math.atan2(bdy, bdx))
                dd = abs((aa - ba + 180) % 360 - 180)
                rep = [(ax+bx)/2, (ay+by)/2, min(dd, 180 - dd)]
        if bestd < W and rep[2] >= MIN_INC and lo <= rep[0] <= hi and lo <= rep[1] <= hi:
            raw.append(rep)
    uniq = []
    for (x, y, inc) in raw:
        merged = False
        for u in uniq:
            if math.hypot(x - u[0], y - u[1]) < dim / 9:
                if inc > u[2]:
                    u[0], u[1], u[2] = x, y, inc
                merged = True; break
        if not merged:
            uniq.append([x, y, inc])
    return [(u[0], u[1]) for u in uniq[:2]]


def conflicts(routes, a, b, dim):
    if a == b:
        return []
    c = centerline_pts(routes, a, b, dim)
    if c:
        return c                       # exact crossing preferred
    return body_pts(routes, a, b, dim) # width-induced fallback


def cell(routes, a, b, dim):
    pts = conflicts(routes, a, b, dim)
    if not pts:
        return [0, 0.0, 0.0, 0.0, 0.0]
    x1, y1 = pts[0]
    x2, y2 = pts[1] if len(pts) >= 2 else (0.0, 0.0)
    return [1, x1/dim, y1/dim, x2/dim, y2/dim]


def fmt(flag, frac):
    if flag == 0 or abs(frac) < 1e-12:
        return "0"
    return f"{frac:.6f}*DIM"


def main():
    dim = parse_args(sys.argv[1:])
    routes = build_routes(dim)
    print("// Auto-generated path-collision matrix (hybrid centerline + body-overlap).")
    print("// Exact crossing point when centerlines cross; body-overlap (W=DIM/15)")
    print("// fallback for width-induced clips. coords tied to DIM (any DIM valid).")
    print("// res[0]=collision flag; res[1..2]=first point; res[3..4]=second point.")
    print("const std::vector<std::vector<std::array<double, 5>>> collisionMatrix = {")
    for a in range(12):
        cells = []
        for b in range(12):
            v = cell(routes, a, b, dim)
            flag = v[0]
            parts = [str(flag)] + [fmt(flag, v[i]) for i in range(1, 5)]
            cells.append("{" + ", ".join(parts) + "}")
        print("    {" + ", ".join(cells) + "},")
    print("};")


if __name__ == "__main__":
    main()