#!/usr/bin/env python3
"""Analyse mp_diag.csv produced by MotionPrediction::diagnosticMP().

Usage:  python3 mp_validation.py mp_diag.csv --dim 1350 --out plots/
Generated by Claude Opus 5
"""
import argparse, os, sys
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

STATE_COLOR = {0: "#888780", 1: "#378ADD", 2: "#E24B4A", 3: "#1D9E75"}
STATE_NAME = {0: "outside", 1: "approach", 2: "middle", 3: "exit"}


def load(path):
    df = pd.read_csv(path)
    df = df.sort_values(["id", "tick"]).reset_index(drop=True)
    df["err"] = np.hypot(df.pred_x - df.act_x, df.pred_y - df.act_y)
    return df


def decompose(df):
    """Split error into along-track and cross-track using realised motion direction.

    along  > 0 : prediction is ahead of the vehicle (overshoot)
    cross  > 0 : prediction is left of the vehicle's path (in x=col, y=row frame)
    """
    out = []
    for vid, g in df.groupby("id", sort=False):
        g = g.sort_values("tick").copy()
        ux = np.array(g.act_x.diff().fillna(0.0), dtype=float)
        uy = np.array(g.act_y.diff().fillna(0.0), dtype=float)
        # backfill the first sample so it is not a zero vector
        if len(ux) > 1:
            ux[0], uy[0] = ux[1], uy[1]
        n = np.hypot(ux, uy)
        n[n < 1e-9] = 1.0
        ux, uy = ux / n, uy / n
        ex = (g.pred_x - g.act_x).to_numpy()
        ey = (g.pred_y - g.act_y).to_numpy()
        g["along"] = ex * ux + ey * uy
        g["cross"] = -ex * uy + ey * ux
        g["moving"] = n > 1e-6
        out.append(g)
    return pd.concat(out).sort_values(["id", "tick"]).reset_index(drop=True)


def draw_intersection(ax, dim):
    lo, hi = 2 * dim / 9, 7 * dim / 9
    ax.add_patch(plt.Rectangle((lo, lo), hi - lo, hi - lo, fill=False,
                               ec="#B4B2A9", lw=0.8, ls="--"))
    a, b = dim / 3 - dim / 16, 2 * dim / 3 + dim / 16
    ax.add_patch(plt.Rectangle((a, a), b - a, b - a, fill=False,
                               ec="#E24B4A", lw=0.8, ls="--"))
    ax.set_xlim(0, dim)
    ax.set_ylim(dim, 0)          # row index increases downward
    ax.set_aspect("equal")
    ax.set_xlabel("x  (col)")
    ax.set_ylabel("y  (row)")


def plot_map(df, dim, path):
    fig, ax = plt.subplots(figsize=(9, 9))
    draw_intersection(ax, dim)
    vmax = max(df.err.quantile(0.95), 1e-6)
    for vid, g in df.groupby("id", sort=False):
        ax.plot(g.act_x, g.act_y, "-", color="#3d3d3a", lw=1.0, alpha=0.7)
        ax.scatter(g.act_x.iloc[0], g.act_y.iloc[0], s=18, c="#3d3d3a", zorder=3)
    sc = None
    for _, r in df.iterrows():
        ax.plot([r.act_x, r.pred_x], [r.act_y, r.pred_y], "-",
                color=plt.cm.plasma(min(r.err / vmax, 1.0)), lw=0.9, alpha=0.9)
    sc = ax.scatter(df.pred_x, df.pred_y, c=df.err.clip(upper=vmax), s=9,
                    cmap="plasma", zorder=4)
    fig.colorbar(sc, ax=ax, label="error [cells]  (clipped at p95)", shrink=0.7)
    ax.set_title("realised path (grey) with prediction error vectors")
    fig.tight_layout()
    fig.savefig(path, dpi=140)
    plt.close(fig)


def plot_error_time(df, path):
    ids = list(df.id.unique())
    fig, axes = plt.subplots(len(ids), 1, figsize=(11, 2.2 * len(ids)),
                             sharex=True, squeeze=False)
    for ax, vid in zip(axes[:, 0], ids):
        g = df[df.id == vid]
        for s, gs in g.groupby("state"):
            ax.scatter(gs.tick, gs.err, s=12, label=f"{s} {STATE_NAME.get(s,'?')}",
                       color=STATE_COLOR.get(s, "#888780"))
        ax.plot(g.tick, g.err, lw=0.6, color="#B4B2A9", zorder=0)
        ax.set_ylabel("err")
        ax.set_title(vid, fontsize=9, loc="left")
        ax.legend(fontsize=7, ncol=4, frameon=False)
    axes[-1, 0].set_xlabel("tick")
    fig.tight_layout()
    fig.savefig(path, dpi=140)
    plt.close(fig)


def plot_decomp(df, path):
    ids = list(df.id.unique())
    fig, axes = plt.subplots(len(ids), 1, figsize=(11, 2.2 * len(ids)),
                             sharex=True, squeeze=False)
    for ax, vid in zip(axes[:, 0], ids):
        g = df[df.id == vid]
        ax.axhline(0, color="#B4B2A9", lw=0.8)
        ax.plot(g.tick, g.along, "-o", ms=3, lw=1.0, color="#D85A30",
                label="along-track (+ = overshoot)")
        ax.plot(g.tick, g.cross, "-o", ms=3, lw=1.0, color="#378ADD",
                label="cross-track")
        ax.set_ylabel("cells")
        ax.set_title(vid, fontsize=9, loc="left")
        ax.legend(fontsize=7, frameon=False)
    axes[-1, 0].set_xlabel("tick")
    fig.tight_layout()
    fig.savefig(path, dpi=140)
    plt.close(fig)


def plot_summary(df, path):
    fig, axes = plt.subplots(1, 3, figsize=(14, 4.2))

    states = sorted(df.state.unique())
    data = [df[df.state == s].err.to_numpy() for s in states]
    axes[0].boxplot(data, tick_labels=[f"{s}\n{STATE_NAME.get(s,'?')}" for s in states])
    axes[0].set_title("error by state")
    axes[0].set_ylabel("err [cells]")

    axes[1].scatter(df.speed, df.err, s=10, c=[STATE_COLOR.get(s, "#888780")
                                               for s in df.state])
    axes[1].set_xlabel("speed at validation [cells/tick]")
    axes[1].set_ylabel("err [cells]")
    axes[1].set_title("error vs speed")
    if len(df) > 2 and df.speed.std() > 1e-9:
        k, q = np.polyfit(df.speed, df.err, 1)
        xs = np.linspace(df.speed.min(), df.speed.max(), 10)
        axes[1].plot(xs, k * xs + q, "--", color="#3d3d3a", lw=1.0,
                     label=f"slope {k:.2f} cells per cell/tick")
        axes[1].legend(fontsize=8, frameon=False)

    mv = df[df.moving]
    axes[2].scatter(mv.along, mv.cross, s=10,
                    c=[STATE_COLOR.get(s, "#888780") for s in mv.state])
    axes[2].axhline(0, color="#B4B2A9", lw=0.8)
    axes[2].axvline(0, color="#B4B2A9", lw=0.8)
    axes[2].set_xlabel("along-track error")
    axes[2].set_ylabel("cross-track error")
    axes[2].set_title("error decomposition")
    axes[2].set_aspect("equal", adjustable="datalim")

    fig.tight_layout()
    fig.savefig(path, dpi=140)
    plt.close(fig)


def report(df):
    print("\n=== per state ===")
    print(df.groupby("state").err.agg(
        n="size", mean="mean", p50="median",
        p95=lambda s: s.quantile(0.95), max="max").round(2).to_string())

    mv = df[df.moving]
    print("\n=== bias (moving samples only) ===")
    print(mv.groupby("state")[["along", "cross"]].mean().round(2).to_string())

    print("\n=== oscillation: sign flips of along-track error per vehicle ===")
    print("  high flip rate at high speed = predictor is hunting around a waypoint")
    rows = []
    for vid, g in mv.groupby("id"):
        g = g.sort_values("tick")
        s = np.sign(g.along.to_numpy())
        flips = int((s[1:] * s[:-1] < 0).sum())
        rows.append((vid, len(g), flips, round(flips / max(len(g) - 1, 1), 2),
                     round(g.speed.mean(), 2), round(g.err.mean(), 2)))
    out = pd.DataFrame(rows, columns=["id", "n", "flips", "flip_rate",
                                      "mean_speed", "mean_err"])
    print(out.sort_values("flip_rate", ascending=False).to_string(index=False))

    print("\n=== stationary predictions (pred identical across ticks) ===")
    for vid, g in df.groupby("id"):
        g = g.sort_values("tick")
        d = np.hypot(g.pred_x.diff(), g.pred_y.diff()).fillna(0)
        frac = float((d < 1e-6).mean())
        if frac > 0.5 and len(g) > 3:
            print(f"  {vid}: {frac:.0%} of predictions unchanged, "
                  f"mean speed {g.speed.mean():.2f}")


def main():
    p = argparse.ArgumentParser()
    p.add_argument("csv")
    p.add_argument("--dim", type=int, default=1350)
    p.add_argument("--out", default="mp_plots")
    p.add_argument("--id", default=None, help="restrict to one vehicle id")
    p.add_argument("--min-speed", type=float, default=None,
                   help="drop samples slower than this")
    a = p.parse_args()

    df = decompose(load(a.csv))
    if a.id:
        df = df[df.id == a.id]
    if a.min_speed is not None:
        df = df[df.speed >= a.min_speed]
    if df.empty:
        sys.exit("no rows after filtering")

    os.makedirs(a.out, exist_ok=True)
    plot_map(df, a.dim, os.path.join(a.out, "map.png"))
    plot_error_time(df, os.path.join(a.out, "error_time.png"))
    plot_decomp(df, os.path.join(a.out, "decomposition.png"))
    plot_summary(df, os.path.join(a.out, "summary.png"))
    report(df)
    print(f"\nplots written to {a.out}/")


if __name__ == "__main__":
    main()
