#!/usr/bin/env python3
"""
Analyze crash/stall screenshots saved by the simulator.

Input : a folder of PNGs named  crash_t<N>.png  or  stall_t<N>.png
        (N = run time at the moment of the event, in ticks).
Output: per category (crash, stall), kept separate:
        - <cat>_heatmap.png   ego position density over the map
        - <cat>_scatter.png   one dot per event
        - <cat>_duration.png  histogram of run durations
        - <cat>_events.csv    one row per file (t, ego_x, ego_y normalized)
        - summary.txt         statistics for both categories

Usage : python analyze_runs.py <png_folder> [-o out_dir] [--bins 40]

All positions are NORMALIZED to [0,1] over the map side, so the result
does not depend on DIM or on the window size.
Generated by Claude Fable 5.1
"""

import argparse
import glob
import os
import re
import sys

import numpy as np
from PIL import Image
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from scipy.ndimage import gaussian_filter

# Colours from SDLRenderer.h (ARGB 0xFF00C864 -> RGB)
EGO_RGB = np.array([0, 200, 100])
COLOR_TOL = 40           # tolerance per channel (screenshot scaling blends edges)
NAME_RE = re.compile(r"^(crash|stall)_t(\d+)\.png$", re.IGNORECASE)


# ---------------------------------------------------------------- parsing
def parse_name(path):
    m = NAME_RE.match(os.path.basename(path))
    if not m:
        return None, None
    return m.group(1).lower(), int(m.group(2))


def map_region(img):
    """Map is the left h x h square; the HUD is to the right of it."""
    a = np.asarray(img.convert("RGB"))
    h = a.shape[0]
    return a[:, :h, :]


def ego_centroid(map_rgb):
    """Returns (x, y) normalized in [0,1], or None if ego not visible."""
    diff = np.abs(map_rgb.astype(int) - EGO_RGB).max(axis=2)
    mask = diff < COLOR_TOL
    n = mask.sum()
    if n == 0:
        return None
    ys, xs = np.nonzero(mask)
    side = map_rgb.shape[0]
    return xs.mean() / side, ys.mean() / side


# ---------------------------------------------------------------- stats
def stats(values):
    v = np.asarray(values, dtype=float)
    if v.size == 0:
        return {}
    return {
        "count": int(v.size),
        "mean": v.mean(),
        "median": np.median(v),
        "std": v.std(ddof=1) if v.size > 1 else 0.0,
        "min": v.min(),
        "max": v.max(),
        "p25": np.percentile(v, 25),
        "p75": np.percentile(v, 75),
    }


def fmt_stats(name, s):
    if not s:
        return f"{name}: no data\n"
    out = [f"{name}: n={s['count']}"]
    d = 3 if s["max"] <= 1.0 else 1
    out += [f"  {k:>7}: {s[k]:.{d}f}" for k in ("mean", "median", "std", "min", "p25", "p75", "max")]
    return "\n".join(out) + "\n"


# ---------------------------------------------------------------- plots
def plot_heatmap(cat, pts, background, out, bins=None, sigma=0.03):
    """sigma: kernel width as fraction of map side."""
    N = 400
    g = (np.arange(N) + 0.5) / N
    X, Y = np.meshgrid(g, g)
    D = np.zeros((N, N))
    for x, y in pts:
        D += np.exp(-((X - x) ** 2 + (Y - y) ** 2) / (2 * sigma ** 2))
    D /= D.max()

    cmap = plt.get_cmap("hot")
    rgba = cmap(D)
    a = np.clip((D - 0.10) / 0.90, 0, 1)
    rgba[..., 3] = a ** 0.6

    fig, ax = plt.subplots(figsize=(7, 7))
    if background is not None:
        ax.imshow(background, cmap="gray", extent=[0, 1, 1, 0])
    ax.imshow(rgba, extent=[0, 1, 1, 0], interpolation="bilinear")
    ax.set_title(f"{cat}: ego position heatmap (n={len(pts)})")
    ax.set_xlabel("x / map side"); ax.set_ylabel("y / map side (down)")
    ax.set_xlim(0, 1); ax.set_ylim(1, 0)
    fig.tight_layout()
    fig.savefig(out, dpi=130)
    plt.close(fig)


def plot_scatter(cat, pts, ts, background, out):
    xs = [p[0] for p in pts]; ys = [p[1] for p in pts]
    fig, ax = plt.subplots(figsize=(7, 7))
    if background is not None:
        ax.imshow(background, cmap="gray", extent=[0, 1, 1, 0], alpha=0.6)
    sc = ax.scatter(xs, ys, c=ts, cmap="viridis", s=40, edgecolor="k")
    fig.colorbar(sc, ax=ax, label="run time t (ticks)")
    ax.set_title(f"{cat}: ego position per event (n={len(pts)})")
    ax.set_xlim(0, 1); ax.set_ylim(1, 0)
    ax.set_xlabel("x / map side"); ax.set_ylabel("y / map side (down)")
    fig.tight_layout()
    fig.savefig(out, dpi=130)
    plt.close(fig)


def plot_duration(cat, ts, out):
    fig, ax = plt.subplots(figsize=(7, 4))
    ax.hist(ts, bins="auto", color="steelblue", edgecolor="k")
    ax.axvline(np.mean(ts), color="r", ls="--", label=f"mean={np.mean(ts):.0f}")
    ax.axvline(np.median(ts), color="orange", ls="--", label=f"median={np.median(ts):.0f}")
    ax.set_title(f"{cat}: run duration until event (n={len(ts)})")
    ax.set_xlabel("t (ticks)"); ax.set_ylabel("count")
    ax.legend()
    fig.tight_layout()
    fig.savefig(out, dpi=130)
    plt.close(fig)


# ---------------------------------------------------------------- main
def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("folder")
    ap.add_argument("-o", "--out", default="analysis_out")
    ap.add_argument("--bins", type=int, default=40, help="heatmap grid per side")
    ap.add_argument("--sigma", type=float, default=0.03, help="kernel width, fraction of map side")
    args = ap.parse_args()

    os.makedirs(args.out, exist_ok=True)
    folder = os.path.expanduser(args.folder)
    files = sorted(f for f in glob.glob(os.path.join(folder, "*"))
                   if f.lower().endswith(".png"))

    data = {"crash": [], "stall": []}   # list of (t, x, y, file)
    background = None
    bg_stack = []
    skipped = []

    for f in files:
        cat, t = parse_name(f)
        if cat is None:
            skipped.append((f, "bad name"))
            continue
        img = Image.open(f)
        region = map_region(img)
        g = np.asarray(Image.fromarray(region).convert("L")).copy()
        veh = (np.abs(region.astype(int) - EGO_RGB).max(axis=2) < COLOR_TOL) | \
              (np.abs(region.astype(int) - np.array([200, 50, 50])).max(axis=2) < COLOR_TOL)
        g[veh] = 80
        bg_stack.append(g)
        c = ego_centroid(region)
        if c is None:
            skipped.append((f, "ego not found"))
            continue
        data[cat].append((t, c[0], c[1], os.path.basename(f)))

    background = np.median(np.stack(bg_stack), axis=0) if bg_stack else None

    lines = ["Run analysis", "=" * 40, f"files scanned: {len(files)}",
             f"skipped: {len(skipped)}", ""]

    for cat in ("crash", "stall"):
        rows = data[cat]
        lines.append("-" * 40)
        if not rows:
            lines.append(f"{cat}: no events\n")
            continue
        ts = [r[0] for r in rows]
        pts = [(r[1], r[2]) for r in rows]

        lines.append(fmt_stats(f"{cat} duration (ticks)", stats(ts)))
        lines.append(fmt_stats(f"{cat} ego x (norm)", stats([p[0] for p in pts])))
        lines.append(fmt_stats(f"{cat} ego y (norm)", stats([p[1] for p in pts])))

        with open(os.path.join(args.out, f"{cat}_events.csv"), "w") as fh:
            fh.write("file,t,ego_x_norm,ego_y_norm\n")
            for t, x, y, name in sorted(rows):
                fh.write(f"{name},{t},{x:.4f},{y:.4f}\n")

        plot_heatmap(cat, pts, background,
                     os.path.join(args.out, f"{cat}_heatmap.png"), sigma=args.sigma)
        plot_scatter(cat, pts, ts, background,
                     os.path.join(args.out, f"{cat}_scatter.png"))
        plot_duration(cat, ts, os.path.join(args.out, f"{cat}_duration.png"))

    if skipped:
        lines.append("-" * 40)
        lines.append("skipped files:")
        lines += [f"  {os.path.basename(f)}: {why}" for f, why in skipped]

    text = "\n".join(lines)
    with open(os.path.join(args.out, "summary.txt"), "w") as fh:
        fh.write(text + "\n")
    print(text)


if __name__ == "__main__":
    main()